<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>{{ $category }} Report - RPT-{{ str_pad($reportId, 5, '0', STR_PAD_LEFT) }}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 9px;
            color: #1a1a1a;
            padding: 20px 24px;
        }
        .header {
            text-align: center;
            margin-bottom: 14px;
            border-bottom: 2px solid #FBBF24;
            padding-bottom: 10px;
        }
        .header h1 { font-size: 14px; font-weight: bold; letter-spacing: 1px; text-transform: uppercase; }
        .header p  { font-size: 8px; color: #555; margin-top: 2px; }
        .report-title { font-size: 11px; font-weight: bold; margin-top: 6px; text-transform: uppercase; color: #333; }
        .report-meta  { font-size: 8px; color: #666; margin-top: 3px; }
        .info-row {
            display: table; width: 100%;
            margin-bottom: 10px; font-size: 8px; color: #555;
        }
        .info-left  { display: table-cell; text-align: left; }
        .info-right { display: table-cell; text-align: right; }
        table { width: 100%; border-collapse: collapse; margin-top: 4px; }
        thead tr { background-color: #FBBF24; }
        thead th {
            padding: 5px 6px; text-align: center;
            font-size: 8px; font-weight: bold; text-transform: uppercase;
            color: #1a1a1a; border: 1px solid #d97706;
        }
        tbody tr:nth-child(even) { background-color: #FFFBEB; }
        tbody tr:nth-child(odd)  { background-color: #ffffff; }
        tbody td {
            padding: 4px 6px; text-align: center;
            font-size: 8px; border: 1px solid #e5e7eb; color: #374151;
        }
        tfoot td {
            padding: 4px 6px; text-align: center;
            font-size: 8px; border: 1px solid #d1d5db;
            background-color: #f3f4f6; font-weight: bold;
            border-top: 2px solid #FBBF24;
        }
        .footer {
            margin-top: 16px; display: table; width: 100%;
            font-size: 8px; color: #6b7280;
            border-top: 1px solid #e5e7eb; padding-top: 8px;
        }
        .footer-left  { display: table-cell; text-align: left; }
        .footer-mid   { display: table-cell; text-align: center; }
        .footer-right { display: table-cell; text-align: right; }
        .badge {
            display: inline-block; padding: 1px 6px;
            border-radius: 9999px; font-size: 7px; font-weight: bold;
        }
        .badge-green  { background-color: #d1fae5; color: #065f46; }
        .badge-yellow { background-color: #fef3c7; color: #92400e; }
        .badge-blue   { background-color: #dbeafe; color: #1e40af; }
        .badge-red    { background-color: #fee2e2; color: #991b1b; }
        .badge-gray   { background-color: #f3f4f6; color: #374151; }
        .empty-row td { text-align: center; padding: 20px; color: #9ca3af; font-style: italic; }
        .logo { display: block; margin: 0 auto 6px auto; max-width: 80px; max-height: 50px; }
    </style>
</head>
<body>

    {{-- HEADER --}}
    <div class="header">
        @php
            $logoPath = public_path('images/ace.jpg');
        @endphp
        @if(file_exists($logoPath))
            <img src="{{ $logoPath }}" alt="MGS Logo" class="logo" />
        @endif
        <h1>Mariviles Graphic Studio</h1>
        <p>Adopted CO. | Mati City</p>
        <div class="report-title">{{ $category }} Report</div>
        <div class="report-meta">
            RPT-{{ str_pad($reportId, 5, '0', STR_PAD_LEFT) }}
            &nbsp;|&nbsp; Type: {{ $reportType }}
            &nbsp;|&nbsp; Coverage: {{ $coverage }}
        </div>
    </div>

    <div class="info-row">
        <span class="info-left">Generated by: <strong>{{ $generatedBy }}</strong></span>
        <span class="info-right">Generated at: <strong>{{ $generatedAt }}</strong></span>
    </div>

    {{-- ORDER --}}
    @if($category === 'Order')
    <table>
        <thead><tr>
            <th>Order ID</th><th>Customer</th><th>Category</th>
            <th>Product Type</th><th>Total Amount</th><th>Order Date</th><th>Status</th>
        </tr></thead>
        <tbody>
            @forelse($rows as $row)
            @php
                $s = $row['status'] ?? 'Pending';
                $cls = match($s) { 'Completed'=>'badge-green','In Progress'=>'badge-yellow','Released'=>'badge-blue','Cancelled'=>'badge-red',default=>'badge-gray' };
            @endphp
            <tr>
                <td>{{ $row['order_id'] ?? '—' }}</td>
                <td>{{ $row['customer_name'] ?? '—' }}</td>
                <td>{{ $row['category_name'] ?? '—' }}</td>
                <td>{{ $row['product_type'] ?? '—' }}</td>
                <td>&#8369;{{ number_format($row['total_amount'] ?? 0, 2) }}</td>
                <td>{{ $row['order_date'] ?? '—' }}</td>
                <td><span class="badge {{ $cls }}">{{ $s }}</span></td>
            </tr>
            @empty
            <tr class="empty-row"><td colspan="7">No records found.</td></tr>
            @endforelse
        </tbody>
    </table>
    @endif

    {{-- DELIVERIES --}}
    @if($category === 'Deliveries')
    <table>
        <thead><tr>
            <th>Delivery ID</th><th>Supplier</th><th>Request Date</th>
            <th>Date Received</th><th>Received By</th><th>Status</th>
        </tr></thead>
        <tbody>
            @forelse($rows as $row)
            @php
                $s = $row['status'] ?? 'Pending';
                $cls = match($s) { 'Delivered'=>'badge-green','Out for Delivery'=>'badge-yellow','For Stock In'=>'badge-blue',default=>'badge-gray' };
            @endphp
            <tr>
                <td>{{ $row['order_id'] ?? '—' }}</td>
                <td>{{ $row['customer_name'] ?? '—' }}</td>
                <td>{{ $row['order_date'] ?? '—' }}</td>
                <td>{{ $row['date_received'] ?? '—' }}</td>
                <td>{{ $row['received_by'] ?? '—' }}</td>
                <td><span class="badge {{ $cls }}">{{ $s }}</span></td>
            </tr>
            @empty
            <tr class="empty-row"><td colspan="6">No records found.</td></tr>
            @endforelse
        </tbody>
    </table>
    @endif

    {{-- JOB ORDER --}}
    @if($category === 'Job Order')
    <table>
        <thead><tr>
            <th>Job Order ID</th><th>Product</th><th>Assigned To</th>
            <th>Est. Time</th><th>Start</th><th>End</th><th>Status</th>
        </tr></thead>
        <tbody>
            @forelse($rows as $row)
            @php
                $s = $row['status'] ?? 'Pending';
                $cls = match($s) { 'Completed'=>'badge-green','In Progress'=>'badge-yellow','Cancelled'=>'badge-red',default=>'badge-gray' };
            @endphp
            <tr>
                <td>{{ $row['order_id'] ?? '—' }}</td>
                <td>{{ $row['product_type'] ?? '—' }}</td>
                <td>{{ $row['customer_name'] ?? '—' }}</td>
                <td>{{ $row['estimated_time'] ?? 0 }}</td>
                <td>{{ $row['order_date'] ?? '—' }}</td>
                <td>{{ $row['end_date'] ?? '—' }}</td>
                <td><span class="badge {{ $cls }}">{{ $s }}</span></td>
            </tr>
            @empty
            <tr class="empty-row"><td colspan="7">No records found.</td></tr>
            @endforelse
        </tbody>
    </table>
    @endif

    {{-- INVENTORY --}}
    @if($category === 'Inventory')
    <table>
        <thead><tr>
            <th>Stock ID</th><th>Product</th><th>Size</th><th>Type</th>
            <th>Current Stock</th><th>Received By</th><th>Stock Level</th>
        </tr></thead>
        <tbody>
            @forelse($rows as $row)
            @php
                $qty = (int)($row['total_amount'] ?? 0);
                $levelText = $qty <= 0 ? 'Out of Stock' : ($qty <= 30 ? 'Low Stock' : ($qty <= 60 ? 'Medium Stock' : 'High Stock'));
                $levelCls  = $qty <= 0 ? 'badge-gray' : ($qty <= 30 ? 'badge-red' : ($qty <= 60 ? 'badge-yellow' : 'badge-green'));
            @endphp
            <tr>
                <td>{{ $row['stock_id'] ?? $row['order_id'] ?? '—' }}</td>
                <td>{{ $row['product_type'] ?? '—' }}</td>
                <td>{{ $row['size'] ?? '—' }}</td>
                <td>{{ $row['product_type'] ?? '—' }}</td>
                <td>{{ $qty }}</td>
                <td>{{ $row['received_by'] ?? '—' }}</td>
                <td><span class="badge {{ $levelCls }}">{{ $levelText }}</span></td>
            </tr>
            @empty
            <tr class="empty-row"><td colspan="7">No records found.</td></tr>
            @endforelse
        </tbody>
    </table>
    @endif

    {{-- STOCK OUT --}}
    @if($category === 'Stock Out')
    <table>
        <thead><tr>
            <th>Stockout ID</th><th>Product</th><th>Employee</th><th>Size</th>
            <th>Qty Out</th><th>Date Out</th><th>Reason</th><th>Status</th>
        </tr></thead>
        <tbody>
            @forelse($rows as $row)
            <tr>
                <td>{{ $row['order_id'] ?? '—' }}</td>
                <td>{{ $row['product_type'] ?? '—' }}</td>
                <td>{{ $row['customer_name'] ?? '—' }}</td>
                <td>{{ $row['size'] ?? '—' }}</td>
                <td>{{ $row['total_amount'] ?? 0 }}</td>
                <td>{{ $row['order_date'] ?? '—' }}</td>
                <td>{{ $row['reason'] ?? '—' }}</td>
                <td><span class="badge badge-gray">{{ $row['status'] ?? '—' }}</span></td>
            </tr>
            @empty
            <tr class="empty-row"><td colspan="8">No records found.</td></tr>
            @endforelse
        </tbody>
    </table>
    @endif

    {{-- STOCK ADJUSTMENT --}}
    @if($category === 'Stock Adjustment')
    <table>
        <thead><tr>
            <th>Adj. ID</th><th>Product</th><th>Type</th><th>Quantity</th>
            <th>Request Date</th><th>Reason</th><th>Status</th><th>Adjusted By</th><th>Approved By</th>
        </tr></thead>
        <tbody>
            @forelse($rows as $row)
            @php
                $s = $row['status'] ?? 'Pending';
                $cls = match($s) { 'Approved'=>'badge-green','Rejected'=>'badge-red',default=>'badge-yellow' };
            @endphp
            <tr>
                <td>{{ $row['order_id'] ?? '—' }}</td>
                <td>{{ $row['product_name'] ?? $row['product_type'] ?? '—' }}</td>
                <td>{{ $row['product_type'] ?? '—' }}</td>
                <td>{{ $row['total_amount'] ?? 0 }}</td>
                <td>{{ $row['order_date'] ?? '—' }}</td>
                <td>{{ $row['reason'] ?? '—' }}</td>
                <td><span class="badge {{ $cls }}">{{ $s }}</span></td>
                <td>{{ $row['adjusted_by'] ?? '—' }}</td>
                <td>{{ $row['approved_by'] ?? '—' }}</td>
            </tr>
            @empty
            <tr class="empty-row"><td colspan="9">No records found.</td></tr>
            @endforelse
        </tbody>
    </table>
    @endif

    {{-- PAYMENT --}}
    @if($category === 'Payment')
    @php
        $totalAmount  = array_sum(array_column($rows, 'total_amount'));
        $totalCash    = array_sum(array_column($rows, 'cash'));
        $totalBalance = array_sum(array_column($rows, 'balance'));
        $totalChange  = array_sum(array_column($rows, 'change_amount'));
    @endphp
    <table>
        <thead><tr>
            <th>Payment ID</th><th>Authorized By</th><th>Method</th><th>Date</th>
            <th>Amount</th><th>Cash</th><th>Balance</th><th>Change</th><th>Status</th>
        </tr></thead>
        <tbody>
            @forelse($rows as $row)
            @php
                $s = trim($row['status'] ?? 'Partial');
                $cls = in_array($s, ['Fully Paid','Full Paid']) ? 'badge-green' : 'badge-yellow';
            @endphp
            <tr>
                <td>P{{ str_pad($row['order_id'] ?? 0, 3, '0', STR_PAD_LEFT) }}</td>
                <td>{{ $row['customer_name'] ?? '—' }}</td>
                <td>{{ $row['product_type'] ?? '—' }}</td>
                <td>{{ $row['order_date'] ?? '—' }}</td>
                <td>&#8369;{{ number_format($row['total_amount'] ?? 0, 2) }}</td>
                <td>&#8369;{{ number_format($row['cash'] ?? 0, 2) }}</td>
                <td>&#8369;{{ number_format($row['balance'] ?? 0, 2) }}</td>
                <td>&#8369;{{ number_format($row['change_amount'] ?? 0, 2) }}</td>
                <td><span class="badge {{ $cls }}">{{ $s }}</span></td>
            </tr>
            @empty
            <tr class="empty-row"><td colspan="9">No records found.</td></tr>
            @endforelse
        </tbody>
        @if(count($rows) > 0)
        <tfoot>
            <tr>
                <td colspan="4" style="text-align:right;">Totals:</td>
                <td>&#8369;{{ number_format($totalAmount, 2) }}</td>
                <td>&#8369;{{ number_format($totalCash, 2) }}</td>
                <td>&#8369;{{ number_format($totalBalance, 2) }}</td>
                <td>&#8369;{{ number_format($totalChange, 2) }}</td>
                <td></td>
            </tr>
        </tfoot>
        @endif
    </table>
    @endif

    {{-- FOOTER --}}
    <div class="footer">
        <span class="footer-left">Generated by: <strong>{{ $generatedBy }}</strong></span>
        <span class="footer-mid">Coverage: {{ $coverage }}</span>
        <span class="footer-right">{{ $generatedAt }}</span>
    </div>

</body>
</html>