@extends('layouts.app')

@section('title', 'Reports')

@section('content')
<div x-data="{
    searchQuery: '',
    placeholderIndex: 0,
    placeholders: [
        'Search reports',
        'Report ID',
        'Payment ID',
        'Category',
        'Report Type',
        'Generated By'
    ],
    nextPlaceholder() {
        this.placeholderIndex = (this.placeholderIndex + 1) % this.placeholders.length;
    },
    filterReports() {
        const query = this.searchQuery.toLowerCase().trim();
        const rows = document.querySelectorAll('#report-table-body tr[data-report]');
        let hasVisibleRows = false;
        
        rows.forEach(row => {
            if (!query) {
                row.style.display = '';
                hasVisibleRows = true;
            } else {
                const searchableText = row.getAttribute('data-search').toLowerCase();
                if (searchableText.includes(query)) {
                    row.style.display = '';
                    hasVisibleRows = true;
                } else {
                    row.style.display = 'none';
                }
            }
        });
        
        // Show/hide empty state
        const emptyState = document.getElementById('reportsEmptyState');
        if (emptyState) {
            emptyState.style.display = hasVisibleRows ? 'none' : '';
        }
        
        return hasVisibleRows;
    }
}" x-cloak>

<header class="mb-8 max-w-7xl mx-auto">
    <div class="flex items-center justify-between border-b pb-3 border-gray-200">
        <h1 class="text-3xl font-bold text-gray-900">Reports</h1>
    </div>
    <p class="text-gray-600 mt-2">Manage reports related to payments, inventory, and categories.</p>
</header>

<!-- Controls -->
<div class="max-w-7xl mx-auto mb-6">
    <div class="flex flex-col md:flex-row items-stretch justify-between gap-4">

        <!-- Search -->
        <div class="relative w-full md:w-80">
            <input type="text" 
                   x-model="searchQuery"
                   @input="filterReports()"
                   :placeholder="placeholders[placeholderIndex]"
                   class="w-full pl-10 pr-10 py-2 border border-gray-300 rounded-xl text-sm focus:ring-2 focus:ring-black focus:outline-none">
            <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none"
                stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                class="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400">
                <circle cx="11" cy="11" r="8" />
                <path d="m21 21-4.3-4.3" />
            </svg>
            </button>
        </div>

        <!-- Add Report -->
        <a href="#"
            class="w-full md:w-auto bg-yellow-400 text-black px-6 py-2 rounded-xl font-semibold flex items-center justify-center space-x-2 hover:bg-yellow-500 transition shadow-md">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none"
                stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="M12 5v14" />
                <path d="M5 12h14" />
            </svg>
            <span>Add New Report</span>
        </a>
    </div>
</div>

<!-- Reports Table -->
<div class="bg-white p-6 rounded-xl shadow max-w-full mx-auto">
    <div class="overflow-x-auto">
        <table id="report-table" class="min-w-full table-auto">
            <thead class="bg-gray-50">
                <tr>
                    <th class="px-4 py-3 text-center text-xs font-bold uppercase text-gray-500">Report ID</th>
                    <th class="px-4 py-3 text-center text-xs font-bold uppercase text-gray-500">Payment ID</th>
                    <th class="px-4 py-3 text-center text-xs font-bold uppercase text-gray-500">Inventory ID</th>
                    <th class="px-4 py-3 text-center text-xs font-bold uppercase text-gray-500">Category</th>
                    <th class="px-4 py-3 text-center text-xs font-bold uppercase text-gray-500">Report Type</th>
                    <th class="px-4 py-3 text-center text-xs font-bold uppercase text-gray-500">Date Created</th>
                    <th class="px-4 py-3 text-center text-xs font-bold uppercase text-gray-500">Generated By</th>
                    <th class="px-4 py-3 text-center text-xs font-bold uppercase text-gray-500">Actions</th>
                </tr>
            </thead>
           <tbody id="report-table-body" class="divide-y divide-gray-100">
                @forelse($reports as $report)
                     <tr class="hover:bg-gray-50" data-report
                         data-search="R{{ str_pad($report->report_id, 3, '0', STR_PAD_LEFT) }} P{{ str_pad($report->payment_id, 3, '0', STR_PAD_LEFT) }} I{{ str_pad($report->inventory_id, 3, '0', STR_PAD_LEFT) }} {{ $report->category }} {{ $report->report_type }} {{ $report->date_created }} {{ $report->generatedBy->fname ?? '' }} {{ $report->generatedBy->lname ?? '' }}">
                        <td class="px-4 py-3 text-center text-gray-800 font-medium">
                            R{{ str_pad($report->report_id, 3, '0', STR_PAD_LEFT) }}
                        </td>
                        <td class="px-4 py-3 text-center text-gray-800 font-medium">
                            P{{ str_pad($report->payment_id, 3, '0', STR_PAD_LEFT) }}
                        </td>
                        <td class="px-4 py-3 text-center text-gray-800 font-medium">
                            I{{ str_pad($report->inventory_id, 3, '0', STR_PAD_LEFT) }}
                        </td>
                        <td class="px-4 py-3 text-center text-gray-600">{{ $report->category }}</td>
                        <td class="px-4 py-3 text-center text-gray-600">{{ $report->report_type }}</td>
                        <td class="px-4 py-3 text-center text-gray-600">{{ $report->date_created }}</td>
                        <td class="px-4 py-3 text-center text-gray-600">
                            {{ $report->generatedBy->fname ?? '—' }} {{ $report->generatedBy->lname ?? '' }}
                        </td>
                        <td class="px-4 py-3 text-center">
                           <div class="flex items-center justify-center space-x-2">
                                <!-- Edit -->
                                <button title="Edit"
                                    class="p-2 rounded-full text-gray-400 hover:text-green-600 hover:bg-green-100 transition-colors duration-200">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="none" stroke="currentColor"
                                        stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                                        <path d="M12 20h9" />
                                        <path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4Z" />
                                    </svg>
                                </button>

                                <!-- Delete Button -->
                                <button title="Delete"
                                    class="p-2 rounded-full text-gray-400 hover:text-red-600 hover:bg-red-100 transition-colors duration-200"
                                    onclick="deleteRow(this)">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="25" fill="none" stroke="currentColor"
                                        stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                                        <path d="M3 4h18v4H3z" />
                                        <path d="M4 8v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8" />
                                        <path d="M10 12h4" />
                                    </svg>
                                </button>
                            </div>
                        </td>
                    </tr>
                @empty
                    <!-- Static Empty State - No Data in Database -->
                    <tr>
                        <td colspan="8" class="px-4 py-16 text-center">
                            <div class="flex flex-col items-center justify-center text-gray-400">
                                <svg class="w-16 h-16 mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/>
                                </svg>
                                <p class="text-lg font-medium text-gray-500">No reports found</p>
                                <p class="text-sm text-gray-400 mt-1">There are currently no reports available</p>
                            </div>
                        </td>
                    </tr>
                @endforelse

                <!-- Dynamic Empty State - Search/Filter No Results -->
                <tr id="reportsEmptyState" style="display: none;">
                    <td colspan="8" class="px-4 py-16 text-center">
                        <div class="flex flex-col items-center justify-center text-gray-400">
                            <svg class="w-16 h-16 mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <circle cx="11" cy="11" r="8" stroke-width="2"/>
                                <path d="m21 21-4.3-4.3" stroke-width="2" stroke-linecap="round"/>
                            </svg>
                            <p class="text-lg font-medium text-gray-500">No reports match your filter</p>
                            <p class="text-sm text-gray-400 mt-1">Try adjusting your search or filter criteria</p>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

<!-- Pagination -->
<div class="custom-pagination mt-6 flex justify-between items-center text-sm text-gray-600 max-w-7xl mx-auto">
    <div id="report-pagination-info">
        Showing 1 to 1 of 3 results
    </div>

    <ul id="report-pagination-links" class="pagination-links flex gap-2">
        <!-- Pagination buttons will be generated by JS -->
    </ul>
</div>

</div>

<script>
const reportRowsPerPage = 5;
const reportTableBody = document.getElementById('report-table-body');
const reportRows = Array.from(reportTableBody.querySelectorAll('tr[data-report]'));
const reportPaginationLinks = document.getElementById('report-pagination-links');
const reportPaginationInfo = document.getElementById('report-pagination-info');

let reportCurrentPage = 1;
const reportTotalPages = Math.ceil(reportRows.length / reportRowsPerPage);

function deleteRow(button) {
    if (confirm("Are you sure you want to remove this row from the table?")) {
        button.closest('tr').remove();
    }
}

function showReportPage(page) {
    reportCurrentPage = page;
    reportRows.forEach(row => row.style.display = 'none');

    const start = (page - 1) * reportRowsPerPage;
    const end = start + reportRowsPerPage;
    reportRows.slice(start, end).forEach(row => row.style.display = '');

    renderReportPagination();
    
    const startItem = reportRows.length ? start + 1 : 0;
    const endItem = end > reportRows.length ? reportRows.length : end;
    reportPaginationInfo.textContent = `Showing ${startItem} to ${endItem} of ${reportRows.length} results`;
}

function renderReportPagination() {
    reportPaginationLinks.innerHTML = '';

    const prev = document.createElement('li');
    prev.className = 'border rounded px-2 py-1';
    prev.innerHTML = reportCurrentPage === 1 ? '« Prev' : `<a href="#">« Prev</a>`;
    if (reportCurrentPage !== 1) prev.querySelector('a').addEventListener('click', e => { e.preventDefault(); showReportPage(reportCurrentPage - 1); });
    reportPaginationLinks.appendChild(prev);

    for (let i = 1; i <= reportTotalPages; i++) {
        const li = document.createElement('li');
        li.className = 'border rounded px-2 py-1' + (i === reportCurrentPage ? ' bg-sky-400 text-white' : '');
        li.innerHTML = i === reportCurrentPage ? i : `<a href="#">${i}</a>`;
        if (i !== reportCurrentPage) li.querySelector('a').addEventListener('click', e => { e.preventDefault(); showReportPage(i); });
        reportPaginationLinks.appendChild(li);
    }

    const next = document.createElement('li');
    next.className = 'border rounded px-2 py-1';
    next.innerHTML = reportCurrentPage === reportTotalPages ? 'Next »' : `<a href="#">Next »</a>`;
    if (reportCurrentPage !== reportTotalPages) next.querySelector('a').addEventListener('click', e => { e.preventDefault(); showReportPage(reportCurrentPage + 1); });
    reportPaginationLinks.appendChild(next);
}

showReportPage(1);
</script>

@endsection