@extends('layouts.app')

@section('title', 'Reports')

@section('content')
<header class="mb-8 max-w-7xl mx-auto">
    <div class="flex items-center justify-between border-b pb-3 border-gray-200">
        <h1 class="text-3xl font-bold text-gray-900">Reports</h1>
    </div>
    <p class="text-gray-600 mt-2">Manage reports related to payments, inventory, and categories.</p>
</header>

<!-- Controls -->
<div class="max-w-7xl mx-auto mb-6">
    <div class="flex flex-col md:flex-row items-stretch justify-between gap-4">

        <!-- Search -->
        <div class="relative w-full md:w-1/4">
            <input type="text" id="report-search" placeholder="Search reports"
                class="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-xl text-sm focus:ring-2 focus:ring-black focus:outline-none">
            <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none"
                stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                class="lucide lucide-search absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400">
                <circle cx="11" cy="11" r="8" />
                <path d="m21 21-4.3-4.3" />
            </svg>
        </div>

        <!-- Add Report -->
        <a href="#"
            class="w-full md:w-auto bg-yellow-400 text-black px-6 py-2 rounded-xl font-semibold flex items-center justify-center space-x-2 hover:bg-yellow-500 transition shadow-md">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none"
                stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                class="lucide lucide-plus">
                <path d="M12 5v14" />
                <path d="M5 12h14" />
            </svg>
            <span>Add New Report</span>
        </a>
    </div>
</div>

<!-- Reports Table -->
<div class="bg-white p-6 rounded-xl shadow max-w-full mx-auto">
    <div class="overflow-x-auto">
        <table id="report-table" class="min-w-full table-auto">
            <thead class="bg-gray-50">
                <tr>
                    <th class="px-4 py-3 text-center text-xs font-bold uppercase text-gray-500">Report ID</th>
                    <th class="px-4 py-3 text-center text-xs font-bold uppercase text-gray-500">Payment ID</th>
                    <th class="px-4 py-3 text-center text-xs font-bold uppercase text-gray-500">Inventory ID</th>
                    <th class="px-4 py-3 text-center text-xs font-bold uppercase text-gray-500">Category</th>
                    <th class="px-4 py-3 text-center text-xs font-bold uppercase text-gray-500">Report Type</th>
                    <th class="px-4 py-3 text-center text-xs font-bold uppercase text-gray-500">Date Created</th>
                    <th class="px-4 py-3 text-center text-xs font-bold uppercase text-gray-500">Generated By</th>
                    <th class="px-4 py-3 text-center text-xs font-bold uppercase text-gray-500">Actions</th>
                </tr>
            </thead>
           <tbody id="report-table-body" class="divide-y divide-gray-100">
                @foreach($reports as $report)
                     <tr class="hover:bg-gray-50">
                        <td class="px-4 py-3 text-center text-gray-800 font-medium">
                            R{{ str_pad($report->report_id, 3, '0', STR_PAD_LEFT) }}
                        </td>
                        <td class="px-4 py-3 text-center text-gray-800 font-medium">
                            P{{ str_pad($report->payment_id, 3, '0', STR_PAD_LEFT) }}
                        </td>
                        <td class="px-4 py-3 text-center text-gray-800 font-medium">
                            I{{ str_pad($report->inventory_id, 3, '0', STR_PAD_LEFT) }}
                        </td>
                        <td class="px-4 py-3 text-center text-gray-600">{{ $report->category }}</td>
                        <td class="px-4 py-3 text-center text-gray-600">{{ $report->report_type }}</td>
                        <td class="px-4 py-3 text-center text-gray-600">{{ $report->date_created }}</td>
                        <td class="px-4 py-3 text-center text-gray-600">
                            {{ $report->generatedBy->fname ?? '—' }} {{ $report->generatedBy->lname ?? '' }}
                        </td>
                        <td class="px-4 py-3 text-center">
                           <div class="flex items-center justify-center space-x-2">
                                <!-- Edit -->
                                <button title="Edit"
                                    class="p-2 rounded-full text-gray-400 hover:text-green-600 hover:bg-green-100 transition-colors duration-200">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="none" stroke="currentColor"
                                        stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-square-pen">
                                        <path d="M12 20h9" />
                                        <path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4Z" />
                                    </svg>
                                </button>

                                <!-- Delete Button -->
                                <button title="Delete"
                                    class="p-2 rounded-full text-gray-400 hover:text-red-600 hover:bg-red-100 transition-colors duration-200"
                                    onclick="deleteRow(this)">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="25" fill="none" stroke="currentColor"
                                        stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-archive">
                                        <path d="M3 4h18v4H3z" />
                                        <path d="M4 8v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8" />
                                        <path d="M10 12h4" />
                                    </svg>
                                </button>
                            </div>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>

<!-- Pagination -->
<div class="custom-pagination mt-6 flex justify-between items-center text-sm text-gray-600">
    <div id="report-pagination-info">
        Showing 1 to 1 of 3 results
    </div>

    <ul id="report-pagination-links" class="pagination-links flex gap-2">
        <!-- Pagination buttons will be generated by JS -->
    </ul>
</div>

<script>
const reportRowsPerPage = 5;
const reportTableBody = document.getElementById('report-table-body');
const reportRows = Array.from(reportTableBody.querySelectorAll('tr'));
const reportPaginationLinks = document.getElementById('report-pagination-links');
const reportPaginationInfo = document.getElementById('report-pagination-info');

let reportCurrentPage = 1;
const reportTotalPages = Math.ceil(reportRows.length / reportRowsPerPage);

function deleteRow(button) {
    if (confirm("Are you sure you want to remove this row from the table?")) {
        button.closest('tr').remove();
    }
}

function showReportPage(page) {
    reportCurrentPage = page;
    reportRows.forEach(row => row.style.display = 'none');

    const start = (page - 1) * reportRowsPerPage;
    const end = start + reportRowsPerPage;
    reportRows.slice(start, end).forEach(row => row.style.display = '');

    renderReportPagination();
    
    const startItem = reportRows.length ? start + 1 : 0;
    const endItem = end > reportRows.length ? reportRows.length : end;
    saPaginationInfo.textContent = `Showing ${startItem} to ${saCurrentPage} of ${saRows.length} results`;
}

function renderReportPagination() {
    reportPaginationLinks.innerHTML = '';

    const prev = document.createElement('li');
    prev.className = 'border rounded px-2 py-1';
    prev.innerHTML = reportCurrentPage === 1 ? '« Prev' : `<a href="#">« Prev</a>`;
    if (reportCurrentPage !== 1) prev.querySelector('a').addEventListener('click', e => { e.preventDefault(); showReportPage(reportCurrentPage - 1); });
    reportPaginationLinks.appendChild(prev);

    for (let i = 1; i <= reportTotalPages; i++) {
        const li = document.createElement('li');
        li.className = 'border rounded px-2 py-1' + (i === reportCurrentPage ? ' bg-sky-400 text-white' : '');
        li.innerHTML = i === reportCurrentPage ? i : `<a href="#">${i}</a>`;
        if (i !== reportCurrentPage) li.querySelector('a').addEventListener('click', e => { e.preventDefault(); showReportPage(i); });
        reportPaginationLinks.appendChild(li);
    }

    const next = document.createElement('li');
    next.className = 'border rounded px-2 py-1';
    next.innerHTML = reportCurrentPage === reportTotalPages ? 'Next »' : `<a href="#">Next »</a>`;
    if (reportCurrentPage !== reportTotalPages) next.querySelector('a').addEventListener('click', e => { e.preventDefault(); showReportPage(reportCurrentPage + 1); });
    reportPaginationLinks.appendChild(next);
}

showReportPage(1);
</script>

@endsection
